name: Lint

on:
  push:

jobs:
  pyrene:
    name: pyrene
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Lint pyrene
      run: (cd pyrene && npm install && npm run lint)
  tuktuktwo:
    name: tuktuktwo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Lint tuktuktwo
      run: (cd tuktuktwo && npm install && npm run lint)
  pyrene-graphs:
    name: pyrene-graphs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Lint pyrene-graphs
      run: (cd pyrene-graphs && npm install && npm run lint)
  kitchensink:
    name: kitchensink
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Lint kitchensink
      run: (cd kitchensink && npm install && npm run lint)
